#!/bin/bash

################################################################################
# MongoDB oplog window size statsd emitter
# Version 0.1
#
# Reports the MongoDB oplog window size in hours to a local statsd server.
################################################################################

# Make sure to quit when running on an arbiter
if [[ "$(mongo --quiet <<< 'rs.isMaster().arbiterOnly')" == "true" ]]; then
  exit 0
fi

hours=$(mongo --quiet --eval "
var ri = db.getReplicationInfo();
var window = new Date(ri.tLast).valueOf() - new Date(ri.tFirst).valueOf();
print(window / (60*60*1000))
")

# Send the metric to localhost:8125
[[ -n "$hours" ]] && echo -n "mongodb.oplog.window_size:${hours}|g|" >/dev/udp/localhost/8125
